// tb_book_equiv.v -- prove the fast book (book.v) is bit-for-bit equivalent to
// the linear-scan book (book_scan.v). Same event stream into both; after each
// event settles, best_bid and order_count must match.
//
// Events come from data/events.txt (generated by tools/itch_to_hex.py, whose
// expected values come from tools/reference_book.py) -- so this also re-checks
// both against the Python model.

`timescale 1ns/1ps

module tb_book_equiv;
    reg         clk = 1'b0;
    reg         rst = 1'b1;
    reg         ev_valid = 1'b0;
    reg  [7:0]  ev_type  = 8'd0;
    reg  [15:0] ev_id    = 16'd0;
    reg  [31:0] ev_price = 32'd0;
    reg  [31:0] ev_shares= 32'd0;

    wire [31:0] fast_best,  scan_best;
    wire [15:0] fast_cnt,   scan_cnt;
    wire        fast_busy,  scan_busy;

    book       u_fast (
        .clk(clk), .rst(rst), .ev_valid(ev_valid), .ev_type(ev_type),
        .ev_id(ev_id), .ev_price(ev_price), .ev_shares(ev_shares),
        .best_bid(fast_best), .order_count(fast_cnt), .busy(fast_busy));

    book_scan  u_scan (
        .clk(clk), .rst(rst), .ev_valid(ev_valid), .ev_type(ev_type),
        .ev_id(ev_id), .ev_price(ev_price), .ev_shares(ev_shares),
        .best_bid(scan_best), .order_count(scan_cnt), .busy(scan_busy));

    always #5 clk = ~clk;

    integer errors = 0, checks = 0;

    task do_event(input [7:0] t, input [15:0] id,
                  input [31:0] pr, input [31:0] sh);
        begin
            @(negedge clk);
            ev_type = t; ev_id = id; ev_price = pr; ev_shares = sh;
            ev_valid = 1'b1;
            @(negedge clk);
            ev_valid = 1'b0;
            wait (fast_busy === 1'b1 || scan_busy === 1'b1);
            wait (fast_busy === 1'b0 && scan_busy === 1'b0);
            repeat (2) @(negedge clk);
        end
    endtask

    integer fd, r, k;
    integer t_i, id_i, pr_i, sh_i, exp_i;

    initial begin
`ifdef DUMP
        $dumpfile("tb_book_equiv.vcd");
        $dumpvars(0, tb_book_equiv);
`endif
        repeat (4) @(negedge clk);
        rst = 1'b0;
        repeat (2) @(negedge clk);

        fd = $fopen("data/events.txt", "r");
        if (fd == 0) begin
            $display("FAIL  cannot open data/events.txt (run `make feed`)");
            $display("TESTS FAILED"); $finish;
        end

        k = 0;
        while (!$feof(fd)) begin
            r = $fscanf(fd, "%h %d %d %d %d\n", t_i, id_i, pr_i, sh_i, exp_i);
            if (r == 5) begin
                do_event(t_i[7:0], id_i[15:0], pr_i, sh_i);
                checks = checks + 1;
                if (fast_best === scan_best && fast_cnt === scan_cnt
                        && fast_best === exp_i) begin
                    // ok
                end else begin
                    errors = errors + 1;
                    $display("FAIL  ev %0d: fast(best=%0d cnt=%0d) scan(best=%0d cnt=%0d) model=%0d",
                             k, fast_best, fast_cnt, scan_best, scan_cnt, exp_i);
                end
                k = k + 1;
            end
        end
        $fclose(fd);

        $display("----");
        $display("events=%0d  mismatches=%0d", checks, errors);
        if (errors == 0 && checks > 0) $display("ALL TESTS PASSED");
        else                           $display("TESTS FAILED");
        $finish;
    end

    initial begin
        #20000000;
        $display("FAIL  timeout");
        $display("TESTS FAILED");
        $finish;
    end
endmodule
