// top.v -- Phase 5 integration: ROM feed -> parser -> book -> display.
//
// A 2-state feeder walks the byte ROM and hands one byte at a time to the
// parser, pausing whenever the book is busy scanning so no decoded event is
// dropped. best_bid drives the 7-segment display (low 16 bits, hex) and its
// low 6 bits drive the onboard LEDs (active low) as a zero-wiring readout.
//
// data/feed.hex and data/feed.vh are generated by tools/itch_to_hex.py.

`timescale 1ns/1ps
`include "data/feed.vh"

// -DREPLAY  : loop the feed, throttle bytes, for a logic-analyzer capture
// -DANIMATE : loop the feed, pace ~12 messages/s, stream per-event telemetry
//             (DDDDDDDD CCC T\n) for tools/viz.py
`ifdef REPLAY
  `define LOOPMODE
`endif
`ifdef ANIMATE
  `define LOOPMODE
`endif

module top (
    input  wire       clk,      // 27 MHz
    input  wire       rst_n,    // onboard button -- NOT used (reads low on this
                                // board; kept only so the .cst pin still maps)
    output wire [5:0] led,      // active low
    output wire [7:0] seg,      // 7-seg cathodes {dp,g,f,e,d,c,b,a}, active low
    output wire [3:0] dig,      // 7-seg anodes, active high, one-hot
    output wire       uart_tx,  // pin 69 -> onboard FT2232 ch B -> host serial
    output wire [7:0] dbg       // J6 header, for the logic analyzer
);
    wire _unused = rst_n;

    // internal power-on reset: assert for the first 16 clocks after config,
    // then release forever. Independent of the (flaky) reset button.
    reg [3:0] por = 4'd0;
    always @(posedge clk)
        if (~por[3]) por <= por + 4'd1;
    wire rst = ~por[3];

    // Optional replay mode (build with -DREPLAY): ~0.4 s after the feed
    // finishes, pulse a restart so the pipeline re-runs -- handy for a
    // free-running logic-analyzer capture. `done` still sits high >99% of the
    // time so the LED verdict stays readable.
    reg        done;
    reg [1:0]  rstate;
    reg [23:0] pcnt;
    localparam R_RUN = 2'd0, R_WAIT = 2'd1, R_RST = 2'd2;
    always @(posedge clk) begin
        if (rst) begin rstate <= R_RUN; pcnt <= 24'd0; end
`ifdef LOOPMODE
        else case (rstate)
            R_RUN:  if (done) begin pcnt <= 24'd0; rstate <= R_WAIT; end
            R_WAIT: if (pcnt == 24'd10_000_000) begin pcnt <= 24'd0; rstate <= R_RST; end
                    else pcnt <= pcnt + 24'd1;
            R_RST:  if (pcnt == 24'd7) begin pcnt <= 24'd0; rstate <= R_RUN; end
                    else pcnt <= pcnt + 24'd1;
            default: rstate <= R_RUN;
        endcase
`endif
    end
    wire frst = rst | (rstate == R_RST);   // resets feeder / parser / book

    // ---- byte ROM + feeder --------------------------------------------
    localparam AW = 15;
    reg  [AW-1:0] addr;
    wire [7:0]    rom_data;

    rom #(.FILE("data/feed.hex"), .DEPTH(32768), .AW(AW)) u_rom (
        .clk(clk), .addr(addr), .data(rom_data)
    );

    localparam F_FETCH = 1'b0, F_PRESENT = 1'b1;
    reg        fstate;
    reg  [7:0] byte_in;
    reg        byte_valid;

    wire       book_busy;

    // In replay mode, throttle the feeder to ~1 byte / 4096 clocks (~150us) so
    // every byte_valid / event_valid / book scan is resolvable on a slow logic
    // analyzer. Normal build: full speed.
`ifdef REPLAY
    localparam [15:0] THROTTLE = 16'd4096;
`else
    localparam [15:0] THROTTLE = 16'd0;
`endif
    reg [15:0] thr;
    always @(posedge clk) thr <= (frst || thr >= THROTTLE) ? 16'd0 : thr + 16'd1;
    wire thr_ok = (thr >= THROTTLE);

    // -DANIMATE: pace the feed to ~12 messages/s so viz.py animates smoothly.
    // Hold the feeder for MPACE clocks after each processed message.
    wire book_done;
`ifdef ANIMATE
  `ifdef SIMPACE
    localparam [23:0] MPACE = 24'd40_000;     // fast-ish; still > 1 UART line
  `else
    localparam [23:0] MPACE = 24'd2_250_000;  // ~12 messages / second
  `endif
`else
    localparam [23:0] MPACE = 24'd0;
`endif
    reg [23:0] mp;
    reg        pacing;
    always @(posedge clk) begin
        if (frst) begin pacing <= 1'b0; mp <= 24'd0; end
        else if (book_done) begin pacing <= 1'b1; mp <= 24'd0; end
        else if (pacing) begin
            if (mp >= MPACE) pacing <= 1'b0;
            else             mp <= mp + 24'd1;
        end
    end
    wire pace_ok = ~pacing;

    always @(posedge clk) begin
        if (frst) begin
            addr       <= {AW{1'b0}};
            fstate     <= F_FETCH;
            done       <= 1'b0;
            byte_in    <= 8'd0;
            byte_valid <= 1'b0;
        end else begin
            byte_valid <= 1'b0;
            case (fstate)
                F_FETCH: begin
                    if (!done) fstate <= F_PRESENT;   // rom_data ready next cycle
                end
                F_PRESENT: begin
                    if (!book_busy && thr_ok && pace_ok) begin
                        byte_in    <= rom_data;
                        byte_valid <= 1'b1;
                        if (addr == `FEED_BYTES - 1) done <= 1'b1;
                        addr       <= addr + 1'b1;
                        fstate     <= F_FETCH;
                    end
                end
            endcase
        end
    end

    // ---- parser ------------------------------------------------------
    wire        p_ev;
    wire [7:0]  p_type;
    wire [15:0] p_id;
    wire [31:0] p_price;
    wire [31:0] p_shares;
    wire        p_is_buy;

    parser u_parser (
        .clk(clk), .rst(frst),
        .byte_in(byte_in), .byte_valid(byte_valid),
        .event_valid(p_ev), .msg_type(p_type), .order_id(p_id),
        .price(p_price), .shares(p_shares), .is_buy(p_is_buy),
        .stock_locate()
    );

    // ---- book ------------------------------------------------------
    // The default build uses the constant-latency CAM book (book.v). The
    // -DANIMATE demo build uses the linear-scan book: it is paced to ~12
    // messages/s so the extra scan latency is invisible, and the CAM book's
    // 256-wide match is right at the 27 MHz timing edge -- adding the
    // telemetry logic pushes it over.
    wire [31:0] best_bid;
    wire [15:0] order_count;

`ifdef ANIMATE
    book_scan u_book (
`else
    book u_book (
`endif
        .clk(clk), .rst(frst),
        .ev_valid(p_ev), .ev_type(p_type), .ev_id(p_id),
        .ev_price(p_price), .ev_shares(p_shares),
        .best_bid(best_bid), .order_count(order_count), .busy(book_busy)
    );

    // one pulse when the book finishes a message; latch its type for telemetry
    reg bb_d;
    always @(posedge clk) bb_d <= book_busy;
    assign book_done = bb_d & ~book_busy;

    reg [7:0] ev_type_l;
    always @(posedge clk) if (p_ev) ev_type_l <= p_type;

    // ---- display ---------------------------------------------------
    display #(.CLK_HZ(27_000_000), .REFRESH_HZ(1000)) u_display (
        .clk(clk), .rst(rst),
        .value(best_bid[15:0]), .seg(seg), .an(dig)
    );

    // ---- LED readout (active low, no wiring needed) ----------------
    //   led[5:3] lit = ROM feed finished
    //   led[2:0] lit = best_bid equals the reference-model value from feed.vh
    //   => all six lit  : pipeline verified on hardware
    //      only 5..3    : feed ran but produced the wrong best bid
    //      all dark     : stuck (clock / reset / config problem)
    wire match = done && (best_bid == `FEED_FINAL_BEST);
    assign led = ~{{3{done}}, {3{match}}};

    // ---- UART readout: stream best_bid as ASCII dollars ------------
    wire [7:0] uart_data;
    wire       uart_send;
    wire       uart_busy;

    readout #(.CLK_HZ(27_000_000), .TICK_HZ(10)) u_readout (
        .clk(clk), .rst(rst), .value(best_bid),
        .ev_stb(book_done), .ev_type(ev_type_l), .ev_sel(4'd0),
        .order_count(order_count),
        .uart_data(uart_data), .uart_send(uart_send), .uart_busy(uart_busy)
    );

    uart_tx #(.CLK_HZ(27_000_000), .BAUD(115200)) u_uart (
        .clk(clk), .rst(rst),
        .data(uart_data), .send(uart_send), .tx(uart_tx), .busy(uart_busy)
    );

    // ---- logic-analyzer taps (J6 header) --------------------------
    //   dbg[0] byte_valid   dbg[1] event_valid   dbg[2] book_busy
    //   dbg[3] done          dbg[4] uart_tx (sigrok can decode it)
    //   dbg[5] best_bid[0]   dbg[6] best_bid[8]  dbg[7] best_bid[16]
    //
    // byte_valid and event_valid are single 37 ns pulses -- far too narrow for
    // a 24 MHz analyzer. Stretch them to ~1.2 us on the taps only (the real
    // signals feeding parser/book are untouched).
    reg [4:0] s_bv, s_ev;
    always @(posedge clk) begin
        s_bv <= byte_valid ? 5'h1F : (s_bv != 0 ? s_bv - 5'd1 : 5'd0);
        s_ev <= p_ev       ? 5'h1F : (s_ev != 0 ? s_ev - 5'd1 : 5'd0);
    end

    assign dbg = {best_bid[16], best_bid[8], best_bid[0], uart_tx,
                  done, book_busy, (s_ev != 0), (s_bv != 0)};

endmodule
