// top.v -- Phase 5 integration: ROM feed -> parser -> book -> display.
//
// A 2-state feeder walks the byte ROM and hands one byte at a time to the
// parser, pausing whenever the book is busy scanning so no decoded event is
// dropped. best_bid drives the 7-segment display (low 16 bits, hex) and its
// low 6 bits drive the onboard LEDs (active low) as a zero-wiring readout.
//
// data/feed.hex and data/feed.vh are generated by tools/itch_to_hex.py.

`timescale 1ns/1ps
`include "data/feed.vh"

module top (
    input  wire       clk,      // 27 MHz
    input  wire       rst_n,    // onboard button, active low
    output wire [5:0] led,      // active low
    output wire [7:0] seg,      // 7-seg cathodes {dp,g,f,e,d,c,b,a}, active low
    output wire [3:0] dig       // 7-seg anodes, active high, one-hot
);
    wire rst = ~rst_n;

    // ---- byte ROM + feeder --------------------------------------------
    localparam AW = 15;
    reg  [AW-1:0] addr;
    wire [7:0]    rom_data;

    rom #(.FILE("data/feed.hex"), .DEPTH(32768), .AW(AW)) u_rom (
        .clk(clk), .addr(addr), .data(rom_data)
    );

    localparam F_FETCH = 1'b0, F_PRESENT = 1'b1;
    reg        fstate;
    reg        done;
    reg  [7:0] byte_in;
    reg        byte_valid;

    wire       book_busy;

    always @(posedge clk) begin
        if (rst) begin
            addr       <= {AW{1'b0}};
            fstate     <= F_FETCH;
            done       <= 1'b0;
            byte_in    <= 8'd0;
            byte_valid <= 1'b0;
        end else begin
            byte_valid <= 1'b0;
            case (fstate)
                F_FETCH: begin
                    if (!done) fstate <= F_PRESENT;   // rom_data ready next cycle
                end
                F_PRESENT: begin
                    if (!book_busy) begin
                        byte_in    <= rom_data;
                        byte_valid <= 1'b1;
                        if (addr == `FEED_BYTES - 1) done <= 1'b1;
                        addr       <= addr + 1'b1;
                        fstate     <= F_FETCH;
                    end
                end
            endcase
        end
    end

    // ---- parser ------------------------------------------------------
    wire        p_ev;
    wire [7:0]  p_type;
    wire [15:0] p_id;
    wire [31:0] p_price;
    wire [31:0] p_shares;
    wire        p_is_buy;

    parser u_parser (
        .clk(clk), .rst(rst),
        .byte_in(byte_in), .byte_valid(byte_valid),
        .event_valid(p_ev), .msg_type(p_type), .order_id(p_id),
        .price(p_price), .shares(p_shares), .is_buy(p_is_buy)
    );

    // ---- book ------------------------------------------------------
    wire [31:0] best_bid;

    book u_book (
        .clk(clk), .rst(rst),
        .ev_valid(p_ev), .ev_type(p_type), .ev_id(p_id),
        .ev_price(p_price), .ev_shares(p_shares),
        .best_bid(best_bid), .busy(book_busy)
    );

    // ---- display ---------------------------------------------------
    display #(.CLK_HZ(27_000_000), .REFRESH_HZ(1000)) u_display (
        .clk(clk), .rst(rst),
        .value(best_bid[15:0]), .seg(seg), .an(dig)
    );

    assign led = ~best_bid[5:0];

endmodule
